/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) casadi_src_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f13 CASADI_PREFIX(f13)
#define casadi_f14 CASADI_PREFIX(f14)
#define casadi_f15 CASADI_PREFIX(f15)
#define casadi_f16 CASADI_PREFIX(f16)
#define casadi_f17 CASADI_PREFIX(f17)
#define casadi_f18 CASADI_PREFIX(f18)
#define casadi_f19 CASADI_PREFIX(f19)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f20 CASADI_PREFIX(f20)
#define casadi_f21 CASADI_PREFIX(f21)
#define casadi_f22 CASADI_PREFIX(f22)
#define casadi_f23 CASADI_PREFIX(f23)
#define casadi_f24 CASADI_PREFIX(f24)
#define casadi_f25 CASADI_PREFIX(f25)
#define casadi_f26 CASADI_PREFIX(f26)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s5[11] = {3, 2, 0, 3, 6, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s6[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s7[33] = {5, 5, 0, 5, 10, 15, 20, 25, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const casadi_int casadi_s8[21] = {5, 3, 0, 5, 10, 15, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const casadi_int casadi_s9[15] = {5, 2, 0, 5, 10, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const casadi_int casadi_s10[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s11[7] = {1, 2, 0, 1, 2, 0, 0};

/* f_fun:(states[3],controls[2],params[0],alg[0])->(xdot[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a2=(a0*a2);
  if (res[0]!=0) res[0][0]=a2;
  a1=sin(a1);
  a0=(a0*a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][2]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int f_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    case 3: return "alg";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "xdot";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* g_fun:(states[3],controls[2],params[0],xdot[3],alg[0])->(zfun) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int g_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    case 3: return "xdot";
    case 4: return "alg";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "zfun";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* vdeFun:(i0[3],i1[2],i2[0],i3[3x3],i4[3x2],i5[0])->(o0[3x3],o1[3x2]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=sin(a1);
  a3=arg[3]? arg[3][2] : 0;
  a4=(a2*a3);
  a4=(a0*a4);
  a4=(-a4);
  if (res[0]!=0) res[0][0]=a4;
  a4=cos(a1);
  a3=(a4*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][1]=a3;
  a3=0.;
  if (res[0]!=0) res[0][2]=a3;
  a5=arg[3]? arg[3][5] : 0;
  a6=(a2*a5);
  a6=(a0*a6);
  a6=(-a6);
  if (res[0]!=0) res[0][3]=a6;
  a5=(a4*a5);
  a5=(a0*a5);
  if (res[0]!=0) res[0][4]=a5;
  if (res[0]!=0) res[0][5]=a3;
  a5=arg[3]? arg[3][8] : 0;
  a2=(a2*a5);
  a2=(a0*a2);
  a2=(-a2);
  if (res[0]!=0) res[0][6]=a2;
  a4=(a4*a5);
  a4=(a0*a4);
  if (res[0]!=0) res[0][7]=a4;
  if (res[0]!=0) res[0][8]=a3;
  a4=cos(a1);
  a5=sin(a1);
  a2=arg[4]? arg[4][2] : 0;
  a6=(a5*a2);
  a6=(a0*a6);
  a4=(a4-a6);
  if (res[1]!=0) res[1][0]=a4;
  a4=sin(a1);
  a1=cos(a1);
  a2=(a1*a2);
  a2=(a0*a2);
  a4=(a4+a2);
  if (res[1]!=0) res[1][1]=a4;
  if (res[1]!=0) res[1][2]=a3;
  a3=arg[4]? arg[4][5] : 0;
  a5=(a5*a3);
  a5=(a0*a5);
  a5=(-a5);
  if (res[1]!=0) res[1][3]=a5;
  a1=(a1*a3);
  a0=(a0*a1);
  if (res[1]!=0) res[1][4]=a0;
  a0=1.;
  if (res[1]!=0) res[1][5]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int vdeFun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int vdeFun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int vdeFun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void vdeFun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int vdeFun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void vdeFun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void vdeFun_incref(void) {
}

CASADI_SYMBOL_EXPORT void vdeFun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int vdeFun_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int vdeFun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real vdeFun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* vdeFun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* vdeFun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* vdeFun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s4;
    case 4: return casadi_s5;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* vdeFun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int vdeFun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int vdeFun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* adj_ERK_fun:(i0[3],i1[2],i2[0],i3[3],i4[0])->(o0[5]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][2] : 0;
  a1=cos(a0);
  a2=arg[1]? arg[1][0] : 0;
  a3=arg[3]? arg[3][1] : 0;
  a4=(a2*a3);
  a1=(a1*a4);
  a4=sin(a0);
  a5=arg[3]? arg[3][0] : 0;
  a2=(a2*a5);
  a4=(a4*a2);
  a1=(a1-a4);
  if (res[0]!=0) res[0][2]=a1;
  a1=sin(a0);
  a1=(a1*a3);
  a0=cos(a0);
  a0=(a0*a5);
  a1=(a1+a0);
  if (res[0]!=0) res[0][3]=a1;
  a1=arg[3]? arg[3][2] : 0;
  if (res[0]!=0) res[0][4]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int adj_ERK_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int adj_ERK_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int adj_ERK_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void adj_ERK_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int adj_ERK_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void adj_ERK_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void adj_ERK_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void adj_ERK_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int adj_ERK_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int adj_ERK_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real adj_ERK_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adj_ERK_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adj_ERK_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* adj_ERK_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* adj_ERK_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int adj_ERK_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int adj_ERK_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* adj_fun:(i0[3],i1[2],i2[0],i3[5],i4[5],i5[3],i6[0],i7[2],i8)->(o0[5],o1[5]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7;
  a0=5.0000000000000000e-01;
  a1=arg[0]? arg[0][0] : 0;
  a2=arg[3]? arg[3][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a4=arg[4]? arg[4][0] : 0;
  a3=(a3*a4);
  a2=(a1-a2);
  a4=(a4*a2);
  a4=(a0*a4);
  a3=(a3+a4);
  if (res[0]!=0) res[0][0]=a3;
  a3=arg[0]? arg[0][1] : 0;
  a4=arg[3]? arg[3][1] : 0;
  a2=(a3-a4);
  a2=(a0*a2);
  a5=arg[4]? arg[4][1] : 0;
  a2=(a2*a5);
  a4=(a3-a4);
  a5=(a5*a4);
  a5=(a0*a5);
  a2=(a2+a5);
  if (res[0]!=0) res[0][1]=a2;
  a2=arg[0]? arg[0][2] : 0;
  a5=arg[3]? arg[3][2] : 0;
  a4=(a2-a5);
  a4=(a0*a4);
  a6=arg[4]? arg[4][2] : 0;
  a4=(a4*a6);
  a2=(a2-a5);
  a6=(a6*a2);
  a6=(a0*a6);
  a4=(a4+a6);
  if (res[0]!=0) res[0][2]=a4;
  a4=arg[1]? arg[1][0] : 0;
  a6=arg[3]? arg[3][3] : 0;
  a2=(a4-a6);
  a5=arg[4]? arg[4][3] : 0;
  a7=(a0*a5);
  a2=(a2*a7);
  a4=(a4-a6);
  a4=(a0*a4);
  a4=(a4*a5);
  a2=(a2+a4);
  if (res[0]!=0) res[0][3]=a2;
  a2=arg[1]? arg[1][1] : 0;
  a4=arg[3]? arg[3][4] : 0;
  a5=(a2-a4);
  a6=arg[4]? arg[4][4] : 0;
  a7=(a0*a6);
  a5=(a5*a7);
  a2=(a2-a4);
  a0=(a0*a2);
  a0=(a0*a6);
  a5=(a5+a0);
  if (res[0]!=0) res[0][4]=a5;
  a1=(a1+a1);
  a5=arg[8]? arg[8][0] : 0;
  a1=(a1*a5);
  if (res[1]!=0) res[1][0]=a1;
  a1=10.;
  a3=(a3-a1);
  a3=(a3+a3);
  a3=(a3*a5);
  if (res[1]!=0) res[1][1]=a3;
  a3=0.;
  if (res[1]!=0) res[1][2]=a3;
  a3=arg[7]? arg[7][0] : 0;
  if (res[1]!=0) res[1][3]=a3;
  a3=arg[7]? arg[7][1] : 0;
  if (res[1]!=0) res[1][4]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int adj_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int adj_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int adj_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void adj_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int adj_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void adj_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void adj_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void adj_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int adj_fun_n_in(void) { return 9;}

CASADI_SYMBOL_EXPORT casadi_int adj_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real adj_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adj_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    case 8: return "i8";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adj_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* adj_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s6;
    case 4: return casadi_s6;
    case 5: return casadi_s0;
    case 6: return casadi_s2;
    case 7: return casadi_s1;
    case 8: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* adj_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int adj_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int adj_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* adjN_fun:(i0[3],i1[0],i2[3],i3[3],i4[0],i5)->(o0[3],o1[3]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6;
  a0=5.0000000000000000e-01;
  a1=arg[0]? arg[0][0] : 0;
  a2=arg[2]? arg[2][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a4=arg[3]? arg[3][0] : 0;
  a3=(a3*a4);
  a2=(a1-a2);
  a4=(a4*a2);
  a4=(a0*a4);
  a3=(a3+a4);
  if (res[0]!=0) res[0][0]=a3;
  a3=arg[0]? arg[0][1] : 0;
  a4=arg[2]? arg[2][1] : 0;
  a2=(a3-a4);
  a2=(a0*a2);
  a5=arg[3]? arg[3][1] : 0;
  a2=(a2*a5);
  a4=(a3-a4);
  a5=(a5*a4);
  a5=(a0*a5);
  a2=(a2+a5);
  if (res[0]!=0) res[0][1]=a2;
  a2=arg[0]? arg[0][2] : 0;
  a5=arg[2]? arg[2][2] : 0;
  a4=(a2-a5);
  a4=(a0*a4);
  a6=arg[3]? arg[3][2] : 0;
  a4=(a4*a6);
  a2=(a2-a5);
  a6=(a6*a2);
  a0=(a0*a6);
  a4=(a4+a0);
  if (res[0]!=0) res[0][2]=a4;
  a1=(a1+a1);
  a4=arg[5]? arg[5][0] : 0;
  a1=(a1*a4);
  if (res[1]!=0) res[1][0]=a1;
  a1=10.;
  a3=(a3-a1);
  a3=(a3+a3);
  a3=(a3*a4);
  if (res[1]!=0) res[1][1]=a3;
  a3=0.;
  if (res[1]!=0) res[1][2]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int adjN_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int adjN_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int adjN_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void adjN_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int adjN_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void adjN_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void adjN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void adjN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int adjN_fun_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int adjN_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real adjN_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adjN_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adjN_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* adjN_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    case 5: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* adjN_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int adjN_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int adjN_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* impl_f_fun:(i0[3],i1[2],i2[0],i3[3],i4[0])->(o0[3]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=arg[3]? arg[3][0] : 0;
  a1=arg[1]? arg[1][0] : 0;
  a2=arg[0]? arg[0][2] : 0;
  a3=cos(a2);
  a3=(a1*a3);
  a0=(a0-a3);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[3]? arg[3][1] : 0;
  a2=sin(a2);
  a1=(a1*a2);
  a0=(a0-a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[3]? arg[3][2] : 0;
  a1=arg[1]? arg[1][1] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][2]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_f_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int impl_f_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_f_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_f_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int impl_f_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_f_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void impl_f_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_f_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int impl_f_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int impl_f_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real impl_f_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_f_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_f_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_f_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_f_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_f_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_f_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* impl_jac_f_x_fun:(i0[3],i1[2],i2[0],i3[3],i4[0])->(o0[3x3]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  a1=arg[1]? arg[1][0] : 0;
  a2=arg[0]? arg[0][2] : 0;
  a3=sin(a2);
  a3=(a1*a3);
  if (res[0]!=0) res[0][6]=a3;
  a2=cos(a2);
  a1=(a1*a2);
  a1=(-a1);
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_x_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f7(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int impl_jac_f_x_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_x_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_f_x_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int impl_jac_f_x_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_f_x_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void impl_jac_f_x_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_f_x_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_f_x_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_f_x_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real impl_jac_f_x_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_x_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_x_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_f_x_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_f_x_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_f_x_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_x_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* impl_jac_f_u_fun:(i0[3],i1[2],i2[0],i3[3],i4[0])->(o0[3x2]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[0]? arg[0][2] : 0;
  a1=cos(a0);
  a1=(-a1);
  if (res[0]!=0) res[0][0]=a1;
  a0=sin(a0);
  a0=(-a0);
  if (res[0]!=0) res[0][1]=a0;
  a0=0.;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  a0=-1.;
  if (res[0]!=0) res[0][5]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_u_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f8(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int impl_jac_f_u_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_u_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_f_u_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int impl_jac_f_u_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_f_u_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void impl_jac_f_u_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_f_u_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_f_u_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_f_u_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real impl_jac_f_u_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_u_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_u_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_f_u_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_f_u_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_f_u_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_u_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* impl_jac_f_xdot_fun:(i0[3],i1[2],i2[0],i3[3],i4[0])->(o0[3x3]) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a1;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_xdot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f9(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int impl_jac_f_xdot_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_xdot_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_f_xdot_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int impl_jac_f_xdot_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_f_xdot_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void impl_jac_f_xdot_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_f_xdot_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_f_xdot_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_f_xdot_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real impl_jac_f_xdot_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_xdot_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_xdot_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_f_xdot_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_f_xdot_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_f_xdot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_xdot_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* impl_jac_f_z_fun:(i0[3],i1[2],i2[0],i3[3],i4[0])->(o0) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_z_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f10(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int impl_jac_f_z_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_z_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_f_z_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int impl_jac_f_z_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_f_z_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void impl_jac_f_z_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_f_z_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_f_z_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_f_z_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real impl_jac_f_z_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_z_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_z_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_f_z_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_f_z_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_f_z_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_z_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* impl_jac_g_x_fun:(i0[3],i1[2],i2[0],i3[3],i4[0])->(o0) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_g_x_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f11(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int impl_jac_g_x_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_g_x_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_g_x_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int impl_jac_g_x_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_g_x_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void impl_jac_g_x_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_g_x_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_g_x_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_g_x_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real impl_jac_g_x_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_g_x_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_g_x_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_g_x_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_g_x_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_g_x_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_g_x_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* impl_jac_g_u_fun:(i0[3],i1[2],i2[0],i3[3],i4[0])->(o0) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_g_u_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f12(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int impl_jac_g_u_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_g_u_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_g_u_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int impl_jac_g_u_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_g_u_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void impl_jac_g_u_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_g_u_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_g_u_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_g_u_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real impl_jac_g_u_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_g_u_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_g_u_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_g_u_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_g_u_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_g_u_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_g_u_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* impl_jac_g_z_fun:(i0[3],i1[2],i2[0],i3[3],i4[0])->(o0) */
static int casadi_f13(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_g_z_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f13(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int impl_jac_g_z_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_g_z_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_g_z_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int impl_jac_g_z_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_g_z_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void impl_jac_g_z_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_g_z_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_g_z_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_g_z_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real impl_jac_g_z_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_g_z_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_g_z_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_g_z_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_g_z_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_g_z_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_g_z_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* h_fun:(states[3],controls[2],params[0])->(h[5]) */
static int casadi_f14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f14(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int h_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "h";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* path_con_fun:(states[3],controls[2],params[0])->(general_con) */
static int casadi_f15(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[0]? arg[0][1] : 0;
  a1=10.;
  a0=(a0-a1);
  a0=casadi_sq(a0);
  a1=arg[0]? arg[0][0] : 0;
  a1=casadi_sq(a1);
  a0=(a0+a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int path_con_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f15(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int path_con_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int path_con_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void path_con_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int path_con_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void path_con_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void path_con_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void path_con_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int path_con_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int path_con_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real path_con_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* path_con_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* path_con_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "general_con";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* path_con_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* path_con_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int path_con_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int path_con_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* path_con_N_fun:(states[3],params[0])->(general_con_N) */
static int casadi_f16(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[0]? arg[0][1] : 0;
  a1=10.;
  a0=(a0-a1);
  a0=casadi_sq(a0);
  a1=arg[0]? arg[0][0] : 0;
  a1=casadi_sq(a1);
  a0=(a0+a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int path_con_N_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f16(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int path_con_N_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int path_con_N_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void path_con_N_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int path_con_N_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void path_con_N_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void path_con_N_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void path_con_N_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int path_con_N_fun_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int path_con_N_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real path_con_N_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* path_con_N_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "states";
    case 1: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* path_con_N_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "general_con_N";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* path_con_N_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* path_con_N_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int path_con_N_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int path_con_N_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* obji_fun:(i0[3],i1[2],i2[0],i3[5],i4[5])->(o0) */
static int casadi_f17(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
  a0=5.0000000000000000e-01;
  a1=arg[0]? arg[0][0] : 0;
  a2=arg[3]? arg[3][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a4=arg[4]? arg[4][0] : 0;
  a3=(a3*a4);
  a1=(a1-a2);
  a3=(a3*a1);
  a1=arg[0]? arg[0][1] : 0;
  a2=arg[3]? arg[3][1] : 0;
  a4=(a1-a2);
  a4=(a0*a4);
  a5=arg[4]? arg[4][1] : 0;
  a4=(a4*a5);
  a1=(a1-a2);
  a4=(a4*a1);
  a3=(a3+a4);
  a4=arg[0]? arg[0][2] : 0;
  a1=arg[3]? arg[3][2] : 0;
  a2=(a4-a1);
  a2=(a0*a2);
  a5=arg[4]? arg[4][2] : 0;
  a2=(a2*a5);
  a4=(a4-a1);
  a2=(a2*a4);
  a3=(a3+a2);
  a2=arg[1]? arg[1][0] : 0;
  a4=arg[3]? arg[3][3] : 0;
  a1=(a2-a4);
  a1=(a0*a1);
  a5=arg[4]? arg[4][3] : 0;
  a1=(a1*a5);
  a2=(a2-a4);
  a1=(a1*a2);
  a3=(a3+a1);
  a1=arg[1]? arg[1][1] : 0;
  a2=arg[3]? arg[3][4] : 0;
  a4=(a1-a2);
  a0=(a0*a4);
  a4=arg[4]? arg[4][4] : 0;
  a0=(a0*a4);
  a1=(a1-a2);
  a0=(a0*a1);
  a3=(a3+a0);
  if (res[0]!=0) res[0][0]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int obji_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f17(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int obji_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int obji_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obji_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int obji_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obji_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void obji_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void obji_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int obji_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int obji_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real obji_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obji_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obji_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obji_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s6;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obji_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int obji_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int obji_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* objN_fun:(i0[3],i1[0],i2[3],i3[3])->(o0) */
static int casadi_f18(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
  a0=5.0000000000000000e-01;
  a1=arg[0]? arg[0][0] : 0;
  a2=arg[2]? arg[2][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a4=arg[3]? arg[3][0] : 0;
  a3=(a3*a4);
  a1=(a1-a2);
  a3=(a3*a1);
  a1=arg[0]? arg[0][1] : 0;
  a2=arg[2]? arg[2][1] : 0;
  a4=(a1-a2);
  a4=(a0*a4);
  a5=arg[3]? arg[3][1] : 0;
  a4=(a4*a5);
  a1=(a1-a2);
  a4=(a4*a1);
  a3=(a3+a4);
  a4=arg[0]? arg[0][2] : 0;
  a1=arg[2]? arg[2][2] : 0;
  a2=(a4-a1);
  a0=(a0*a2);
  a2=arg[3]? arg[3][2] : 0;
  a0=(a0*a2);
  a4=(a4-a1);
  a0=(a0*a4);
  a3=(a3+a0);
  if (res[0]!=0) res[0][0]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int objN_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f18(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int objN_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int objN_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void objN_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int objN_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void objN_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void objN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void objN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int objN_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int objN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real objN_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* objN_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* objN_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* objN_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* objN_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int objN_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int objN_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* gi_fun:(i0[3],i1[2],i2[0],i3[5],i4[5])->(o0[3],o1[2]) */
static int casadi_f19(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
  a0=5.0000000000000000e-01;
  a1=arg[0]? arg[0][0] : 0;
  a2=arg[3]? arg[3][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a4=arg[4]? arg[4][0] : 0;
  a3=(a3*a4);
  a1=(a1-a2);
  a4=(a4*a1);
  a4=(a0*a4);
  a3=(a3+a4);
  if (res[0]!=0) res[0][0]=a3;
  a3=arg[0]? arg[0][1] : 0;
  a4=arg[3]? arg[3][1] : 0;
  a1=(a3-a4);
  a1=(a0*a1);
  a2=arg[4]? arg[4][1] : 0;
  a1=(a1*a2);
  a3=(a3-a4);
  a2=(a2*a3);
  a2=(a0*a2);
  a1=(a1+a2);
  if (res[0]!=0) res[0][1]=a1;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[3]? arg[3][2] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a4=arg[4]? arg[4][2] : 0;
  a3=(a3*a4);
  a1=(a1-a2);
  a4=(a4*a1);
  a4=(a0*a4);
  a3=(a3+a4);
  if (res[0]!=0) res[0][2]=a3;
  a3=arg[1]? arg[1][0] : 0;
  a4=arg[3]? arg[3][3] : 0;
  a1=(a3-a4);
  a2=arg[4]? arg[4][3] : 0;
  a5=(a0*a2);
  a1=(a1*a5);
  a3=(a3-a4);
  a3=(a0*a3);
  a3=(a3*a2);
  a1=(a1+a3);
  if (res[1]!=0) res[1][0]=a1;
  a1=arg[1]? arg[1][1] : 0;
  a3=arg[3]? arg[3][4] : 0;
  a2=(a1-a3);
  a4=arg[4]? arg[4][4] : 0;
  a5=(a0*a4);
  a2=(a2*a5);
  a1=(a1-a3);
  a0=(a0*a1);
  a0=(a0*a4);
  a2=(a2+a0);
  if (res[1]!=0) res[1][1]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int gi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f19(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int gi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int gi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int gi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void gi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void gi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int gi_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int gi_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real gi_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gi_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gi_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s6;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int gi_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* gN_fun:(i0[3],i1[0],i2[3],i3[3])->(o0[3]) */
static int casadi_f20(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=5.0000000000000000e-01;
  a1=arg[0]? arg[0][0] : 0;
  a2=arg[2]? arg[2][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a4=arg[3]? arg[3][0] : 0;
  a3=(a3*a4);
  a1=(a1-a2);
  a4=(a4*a1);
  a4=(a0*a4);
  a3=(a3+a4);
  if (res[0]!=0) res[0][0]=a3;
  a3=arg[0]? arg[0][1] : 0;
  a4=arg[2]? arg[2][1] : 0;
  a1=(a3-a4);
  a1=(a0*a1);
  a2=arg[3]? arg[3][1] : 0;
  a1=(a1*a2);
  a3=(a3-a4);
  a2=(a2*a3);
  a2=(a0*a2);
  a1=(a1+a2);
  if (res[0]!=0) res[0][1]=a1;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[2]? arg[2][2] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a4=arg[3]? arg[3][2] : 0;
  a3=(a3*a4);
  a1=(a1-a2);
  a4=(a4*a1);
  a0=(a0*a4);
  a3=(a3+a0);
  if (res[0]!=0) res[0][2]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int gN_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f20(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int gN_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int gN_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gN_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int gN_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gN_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void gN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void gN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int gN_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int gN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real gN_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gN_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gN_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gN_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gN_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gN_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int gN_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* Hi_fun:(i0[3],i1[2],i2[0],i3[5],i4[5])->(o0[5x5]) */
static int casadi_f21(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a1;
  if (res[0]!=0) res[0][9]=a1;
  if (res[0]!=0) res[0][10]=a1;
  if (res[0]!=0) res[0][11]=a1;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a1;
  if (res[0]!=0) res[0][14]=a1;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a1;
  if (res[0]!=0) res[0][17]=a1;
  if (res[0]!=0) res[0][18]=a0;
  if (res[0]!=0) res[0][19]=a1;
  if (res[0]!=0) res[0][20]=a1;
  if (res[0]!=0) res[0][21]=a1;
  if (res[0]!=0) res[0][22]=a1;
  if (res[0]!=0) res[0][23]=a1;
  if (res[0]!=0) res[0][24]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Hi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f21(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Hi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Hi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Hi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Hi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Hi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Hi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Hi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Hi_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Hi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Hi_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Hi_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Hi_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Hi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s6;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Hi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Hi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Hi_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* HN_fun:(i0[3],i1[0],i2[3],i3[3])->(o0[3x3]) */
static int casadi_f22(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a1;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int HN_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f22(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int HN_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int HN_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void HN_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int HN_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void HN_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void HN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void HN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int HN_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int HN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real HN_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* HN_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* HN_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* HN_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* HN_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int HN_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int HN_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* Ji_fun:(i0[3],i1[2],i2[0],i3[5],i4[5])->(o0[5x3],o1[5x2]) */
static int casadi_f23(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[4]? arg[4][0] : 0;
  a0=sqrt(a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=0.;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  a1=arg[4]? arg[4][1] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][6]=a1;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a0;
  a1=arg[4]? arg[4][2] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][12]=a1;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  if (res[1]!=0) res[1][2]=a0;
  a1=arg[4]? arg[4][3] : 0;
  a1=sqrt(a1);
  if (res[1]!=0) res[1][3]=a1;
  if (res[1]!=0) res[1][4]=a0;
  if (res[1]!=0) res[1][5]=a0;
  if (res[1]!=0) res[1][6]=a0;
  if (res[1]!=0) res[1][7]=a0;
  if (res[1]!=0) res[1][8]=a0;
  a0=arg[4]? arg[4][4] : 0;
  a0=sqrt(a0);
  if (res[1]!=0) res[1][9]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Ji_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f23(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Ji_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Ji_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Ji_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Ji_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Ji_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Ji_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Ji_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Ji_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Ji_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Ji_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ji_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ji_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Ji_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s6;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Ji_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    case 1: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Ji_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Ji_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* JN_fun:(i0[3],i1[0],i2[3],i3[3])->(o0[3x3]) */
static int casadi_f24(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[3]? arg[3][0] : 0;
  a0=sqrt(a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=0.;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  a1=arg[3]? arg[3][1] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[3]? arg[3][2] : 0;
  a0=sqrt(a0);
  if (res[0]!=0) res[0][8]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int JN_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f24(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int JN_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int JN_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void JN_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int JN_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void JN_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void JN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void JN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int JN_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int JN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real JN_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* JN_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* JN_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* JN_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* JN_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int JN_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int JN_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* Ci_fun:(i0[3],i1[2],i2[0])->(o0[1x3],o1[1x2]) */
static int casadi_f25(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[0]? arg[0][0] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][1] : 0;
  a1=10.;
  a0=(a0-a1);
  a0=(a0+a0);
  if (res[0]!=0) res[0][1]=a0;
  a0=0.;
  if (res[0]!=0) res[0][2]=a0;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Ci_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f25(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Ci_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Ci_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Ci_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Ci_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Ci_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Ci_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Ci_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Ci_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Ci_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Ci_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ci_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ci_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Ci_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Ci_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    case 1: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Ci_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Ci_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* CN_fun:(i0[3],i1[0])->(o0[1x3]) */
static int casadi_f26(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[0]? arg[0][0] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][1] : 0;
  a1=10.;
  a0=(a0-a1);
  a0=(a0+a0);
  if (res[0]!=0) res[0][1]=a0;
  a0=0.;
  if (res[0]!=0) res[0][2]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int CN_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f26(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int CN_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int CN_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void CN_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int CN_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void CN_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void CN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void CN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int CN_fun_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int CN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real CN_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* CN_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* CN_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* CN_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* CN_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int CN_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int CN_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
